//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.12 at 10:52:11 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://user.net/time-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.user.time_service;
